---
- hosts: local
  remote_user: support
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: create container
    command: 'sudo lxc launch images:centos/7 {{hostname}}'
